# 启动端口
server:
 port: 8080

## 数据库配置
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver


## Mybatis
mybatis:
  mapper-locations: mapper/*.xml #xml文件
  type-aliases-package: com.github.springbootmiaosha.entity #实体类

## 日志配置
logging:
  config: src/main/resources/logback.xml
  level:
    com.github.springbootmiaosha.dao: trace

